"""added followers table

Revision ID: b00dbca81e15
Revises: cd126382f5fa
Create Date: 2022-05-14 18:39:13.079548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00dbca81e15'
down_revision = 'cd126382f5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('followerID', sa.String(length=32), nullable=True),
    sa.Column('followedID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['followedID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['followerID'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
